services:
  mcp-server:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    env_file:
      - .env
    image: ghcr.io/madebymatthew/mcp-server-for-mc-hosting:latest
    restart: unless-stopped
